// Sample book data for Biblioteca prototype.
// Mix of real Portuguese literature & history titles with plausible call numbers,
// modeled on the scraped JSON shape (original + normalized + lookups).

window.LIBRARY_BOOKS = [
  {
    id: 69,
    call_number: "J2128",
    prefix: "J",
    title: "Portugal, a Terra e o Homem",
    title_pt: "Portugal, a Terra e o Homem",
    author: "David Mourão-Ferreira",
    author_raw: "Ferreira, David Mourão & Seixo, Maria Alzira",
    subject: "Education",
    subject_pt: "Educação",
    year: 1979,
    publisher: "Fundação Calouste Gulbenkian",
    publisher_city: "Lisboa",
    notes: "Vol. II — Antologia de textos de escritores do século XX. II Volume-1 and 2 Series.",
    has_cover: false,
    added: "2026-05-21",
    lookups: {
      bnp: 3, google_books: 5, loc: 5, internet_archive: 0,
      open_library: 0, bn_digital: 5, cultura_acores: "err"
    },
    digital_copies: [
      "https://bndigital.bnportugal.gov.pt/records/item/27394-a-terra-e-o-homem"
    ],
    best_match_source: "bnp",
    confidence: "high"
  },
  {
    id: 1, call_number: "L0142", prefix: "L",
    title: "Os Lusíadas", title_pt: "Os Lusíadas",
    author: "Luís Vaz de Camões", author_raw: "Camões, Luís Vaz de",
    subject: "Literature", subject_pt: "Literatura",
    year: 1572, publisher: "António Gonçalves", publisher_city: "Lisboa",
    notes: "Epic poem in ten cantos. 1932 facsimile edition.",
    has_cover: true, added: "2026-05-18",
    lookups: { bnp: 18, google_books: 12, loc: 8, internet_archive: 4, open_library: 6, bn_digital: 9 },
    digital_copies: ["https://bndigital.bnportugal.gov.pt/records/item/1234-lusiadas"],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 2, call_number: "P0089", prefix: "P",
    title: "Mensagem", title_pt: "Mensagem",
    author: "Fernando Pessoa", author_raw: "Pessoa, Fernando",
    subject: "Poetry", subject_pt: "Poesia",
    year: 1934, publisher: "Parceria António Maria Pereira", publisher_city: "Lisboa",
    notes: "First edition. Only book of poetry in Portuguese published in his lifetime.",
    has_cover: true, added: "2026-05-20",
    lookups: { bnp: 9, google_books: 11, loc: 5, internet_archive: 3, open_library: 4, bn_digital: 6 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 3, call_number: "L0631", prefix: "L",
    title: "Os Maias", title_pt: "Os Maias",
    author: "José Maria de Eça de Queirós", author_raw: "Queirós, J. M. de Eça",
    subject: "Literature", subject_pt: "Literatura",
    year: 1888, publisher: "Livraria Internacional", publisher_city: "Porto",
    notes: "Episódios da Vida Romântica. Two-volume original printing.",
    has_cover: true, added: "2026-05-17",
    lookups: { bnp: 14, google_books: 8, loc: 6, internet_archive: 2, open_library: 5, bn_digital: 4 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 4, call_number: "L0455", prefix: "L",
    title: "Amor de Perdição", title_pt: "Amor de Perdição",
    author: "Camilo Castelo Branco", author_raw: "Branco, Camilo Castelo",
    subject: "Literature", subject_pt: "Literatura",
    year: 1862, publisher: "Tipografia Sebastião José Pereira", publisher_city: "Porto",
    notes: "Memórias d'uma Família. Romantic novel, written in 15 days.",
    has_cover: false, added: "2026-05-16",
    lookups: { bnp: 8, google_books: 6, loc: 3, internet_archive: 2, open_library: 3, bn_digital: 4 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 5, call_number: "L0892", prefix: "L",
    title: "Memorial do Convento", title_pt: "Memorial do Convento",
    author: "José Saramago", author_raw: "Saramago, José",
    subject: "Literature", subject_pt: "Literatura",
    year: 1982, publisher: "Editorial Caminho", publisher_city: "Lisboa",
    notes: "Set during the construction of Mafra Convent. Nobel laureate.",
    has_cover: true, added: "2026-05-15",
    lookups: { bnp: 11, google_books: 14, loc: 7, internet_archive: 1, open_library: 8, bn_digital: 3 },
    digital_copies: [],
    best_match_source: "google_books", confidence: "high"
  },
  {
    id: 6, call_number: "A0124", prefix: "A",
    title: "Sermões", title_pt: "Sermões",
    author: "Padre António Vieira", author_raw: "Vieira, Padre António",
    subject: "Religion", subject_pt: "Religião",
    year: 1679, publisher: "Officina de Miguel Deslandes", publisher_city: "Lisboa",
    notes: "Tomo Primeiro. Jesuit sermons, foundational Baroque prose.",
    has_cover: false, added: "2026-05-14",
    lookups: { bnp: 22, google_books: 4, loc: 5, internet_archive: 6, open_library: 2, bn_digital: 11 },
    digital_copies: ["https://bndigital.bnportugal.gov.pt/records/item/2244-sermoes"],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 7, call_number: "D0512", prefix: "D",
    title: "Peregrinação", title_pt: "Peregrinação",
    author: "Fernão Mendes Pinto", author_raw: "Pinto, Fernão Mendes",
    subject: "Travel", subject_pt: "Viagens",
    year: 1614, publisher: "Pedro Crasbeeck", publisher_city: "Lisboa",
    notes: "Travels through Asia, 1537–1558. Posthumous publication.",
    has_cover: false, added: "2026-05-13",
    lookups: { bnp: 7, google_books: 9, loc: 4, internet_archive: 5, open_library: 3, bn_digital: 6 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 8, call_number: "D0299", prefix: "D",
    title: "Viagens na Minha Terra", title_pt: "Viagens na Minha Terra",
    author: "Almeida Garrett", author_raw: "Garrett, João Baptista da Silva Leitão de Almeida",
    subject: "Travel", subject_pt: "Viagens",
    year: 1846, publisher: "Imprensa Nacional", publisher_city: "Lisboa",
    notes: "Hybrid travel narrative and digressive novel.",
    has_cover: true, added: "2026-05-12",
    lookups: { bnp: 9, google_books: 7, loc: 4, internet_archive: 3, open_library: 4, bn_digital: 5 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 9, call_number: "L0644", prefix: "L",
    title: "A Cidade e as Serras", title_pt: "A Cidade e as Serras",
    author: "José Maria de Eça de Queirós", author_raw: "Queirós, J. M. de Eça",
    subject: "Literature", subject_pt: "Literatura",
    year: 1901, publisher: "Lello & Irmão", publisher_city: "Porto",
    notes: "Posthumous. City vs. countryside dialectic.",
    has_cover: false, added: "2026-05-11",
    lookups: { bnp: 12, google_books: 6, loc: 5, internet_archive: 2, open_library: 4, bn_digital: 3 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 10, call_number: "C0048", prefix: "C",
    title: "História de Portugal", title_pt: "História de Portugal",
    author: "Joaquim Pedro de Oliveira Martins", author_raw: "Martins, J. P. de Oliveira",
    subject: "History", subject_pt: "História",
    year: 1879, publisher: "Bertrand", publisher_city: "Lisboa",
    notes: "Two volumes. Definitive 19th-century synthesis.",
    has_cover: false, added: "2026-05-10",
    lookups: { bnp: 15, google_books: 4, loc: 7, internet_archive: 8, open_library: 3, bn_digital: 9 },
    digital_copies: [],
    best_match_source: "loc", confidence: "high"
  },
  {
    id: 11, call_number: "L0771", prefix: "L",
    title: "A Selva", title_pt: "A Selva",
    author: "Ferreira de Castro", author_raw: "Castro, Ferreira de",
    subject: "Literature", subject_pt: "Literatura",
    year: 1930, publisher: "Guimarães Editores", publisher_city: "Lisboa",
    notes: "Brazilian Amazon as autobiographical fiction.",
    has_cover: true, added: "2026-05-09",
    lookups: { bnp: 6, google_books: 5, loc: 2, internet_archive: 1, open_library: 3, bn_digital: 2 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 12, call_number: "L0908", prefix: "L",
    title: "Aparição", title_pt: "Aparição",
    author: "Vergílio Ferreira", author_raw: "Ferreira, Vergílio",
    subject: "Literature", subject_pt: "Literatura",
    year: 1959, publisher: "Portugália Editora", publisher_city: "Lisboa",
    notes: "Existentialist novel set in Évora.",
    has_cover: false, added: "2026-05-08",
    lookups: { bnp: 5, google_books: 6, loc: 3, internet_archive: 1, open_library: 4, bn_digital: 2 },
    digital_copies: [],
    best_match_source: "google_books", confidence: "medium"
  },
  {
    id: 13, call_number: "L0822", prefix: "L",
    title: "Sinais de Fogo", title_pt: "Sinais de Fogo",
    author: "Jorge de Sena", author_raw: "Sena, Jorge de",
    subject: "Literature", subject_pt: "Literatura",
    year: 1979, publisher: "Edições 70", publisher_city: "Lisboa",
    notes: "Posthumous. Spanish Civil War seen from Figueira da Foz.",
    has_cover: false, added: "2026-05-07",
    lookups: { bnp: 4, google_books: 3, loc: 2, internet_archive: 0, open_library: 2, bn_digital: 1 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 14, call_number: "L0701", prefix: "L",
    title: "O Crime do Padre Amaro", title_pt: "O Crime do Padre Amaro",
    author: "José Maria de Eça de Queirós", author_raw: "Queirós, J. M. de Eça",
    subject: "Literature", subject_pt: "Literatura",
    year: 1875, publisher: "Tipografia Castro Irmão", publisher_city: "Lisboa",
    notes: "Originally serialized in Revista Ocidental.",
    has_cover: true, added: "2026-05-06",
    lookups: { bnp: 11, google_books: 8, loc: 5, internet_archive: 4, open_library: 6, bn_digital: 3 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 15, call_number: "T0034", prefix: "T",
    title: "Frei Luís de Sousa", title_pt: "Frei Luís de Sousa",
    author: "Almeida Garrett", author_raw: "Garrett, J. B. de Almeida",
    subject: "Drama", subject_pt: "Teatro",
    year: 1844, publisher: "Imprensa Nacional", publisher_city: "Lisboa",
    notes: "Three-act tragedy in prose. Romantic theatre.",
    has_cover: false, added: "2026-05-05",
    lookups: { bnp: 6, google_books: 3, loc: 2, internet_archive: 1, open_library: 2, bn_digital: 2 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 16, call_number: "P0156", prefix: "P",
    title: "Folhas Caídas", title_pt: "Folhas Caídas",
    author: "Almeida Garrett", author_raw: "Garrett, J. B. de Almeida",
    subject: "Poetry", subject_pt: "Poesia",
    year: 1853, publisher: "Imprensa Nacional", publisher_city: "Lisboa",
    notes: "Late lyric collection — pivots from neoclassical to confessional.",
    has_cover: false, added: "2026-05-04",
    lookups: { bnp: 5, google_books: 2, loc: 1, internet_archive: 1, open_library: 2, bn_digital: 2 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 17, call_number: "L0588", prefix: "L",
    title: "Húmus", title_pt: "Húmus",
    author: "Raul Brandão", author_raw: "Brandão, Raul",
    subject: "Literature", subject_pt: "Literatura",
    year: 1917, publisher: "Renascença Portuguesa", publisher_city: "Porto",
    notes: "Decadent prose-poem novel.",
    has_cover: false, added: "2026-05-03",
    lookups: { bnp: 3, google_books: 2, loc: 1, internet_archive: 0, open_library: 1, bn_digital: 1 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "low"
  },
  {
    id: 18, call_number: "P0011", prefix: "P",
    title: "Cancioneiro da Vaticana", title_pt: "Cancioneiro da Vaticana",
    author: "Anonymous", author_raw: "[Compiled, anon.]",
    subject: "Poetry", subject_pt: "Poesia",
    year: 1875, publisher: "Imprensa Nacional", publisher_city: "Lisboa",
    notes: "Medieval Galician-Portuguese lyric, 13th-14th c. Theophilo Braga edition.",
    has_cover: false, added: "2026-05-02",
    lookups: { bnp: 4, google_books: 1, loc: 2, internet_archive: 3, open_library: 1, bn_digital: 5 },
    digital_copies: [],
    best_match_source: "bn_digital", confidence: "medium"
  },
  {
    id: 19, call_number: "L0961", prefix: "L",
    title: "Bichos", title_pt: "Bichos",
    author: "Miguel Torga", author_raw: "Torga, Miguel",
    subject: "Literature", subject_pt: "Literatura",
    year: 1940, publisher: "Coimbra Editora", publisher_city: "Coimbra",
    notes: "Short stories told from the perspective of animals.",
    has_cover: true, added: "2026-05-01",
    lookups: { bnp: 7, google_books: 4, loc: 3, internet_archive: 1, open_library: 3, bn_digital: 2 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 20, call_number: "L0934", prefix: "L",
    title: "Manhã Submersa", title_pt: "Manhã Submersa",
    author: "Vergílio Ferreira", author_raw: "Ferreira, Vergílio",
    subject: "Literature", subject_pt: "Literatura",
    year: 1954, publisher: "Sá da Costa", publisher_city: "Lisboa",
    notes: "Seminary novel based on the author's youth.",
    has_cover: false, added: "2026-04-30",
    lookups: { bnp: 4, google_books: 3, loc: 2, internet_archive: 1, open_library: 3, bn_digital: 1 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "medium"
  },
  {
    id: 21, call_number: "T0019", prefix: "T",
    title: "Auto da Barca do Inferno", title_pt: "Auto da Barca do Inferno",
    author: "Gil Vicente", author_raw: "Vicente, Gil",
    subject: "Drama", subject_pt: "Teatro",
    year: 1517, publisher: "[manuscrito]", publisher_city: "Lisboa",
    notes: "Allegorical morality play. 1928 critical edition.",
    has_cover: false, added: "2026-04-29",
    lookups: { bnp: 8, google_books: 4, loc: 3, internet_archive: 2, open_library: 3, bn_digital: 4 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 22, call_number: "C0211", prefix: "C",
    title: "Os Descobrimentos Portugueses", title_pt: "Os Descobrimentos Portugueses",
    author: "Jaime Cortesão", author_raw: "Cortesão, Jaime",
    subject: "History", subject_pt: "História",
    year: 1960, publisher: "Arcádia", publisher_city: "Lisboa",
    notes: "Six-volume history of the Portuguese discoveries.",
    has_cover: false, added: "2026-04-28",
    lookups: { bnp: 9, google_books: 3, loc: 5, internet_archive: 2, open_library: 2, bn_digital: 4 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "high"
  },
  {
    id: 23, call_number: "B0067", prefix: "B",
    title: "O Sentido da Vida", title_pt: "O Sentido da Vida",
    author: "Leonardo Coimbra", author_raw: "Coimbra, Leonardo",
    subject: "Philosophy", subject_pt: "Filosofia",
    year: 1916, publisher: "Renascença Portuguesa", publisher_city: "Porto",
    notes: "Foundational text of Portuguese 'criacionismo'.",
    has_cover: false, added: "2026-04-27",
    lookups: { bnp: 3, google_books: 1, loc: 0, internet_archive: 0, open_library: 1, bn_digital: 1 },
    digital_copies: [],
    best_match_source: "bnp", confidence: "low"
  },
];

// Subject metadata — display label + accent tile color (azulejo palette range).
window.LIBRARY_SUBJECTS = [
  { key: "Literature",  pt: "Literatura", prefix: "L", tile: "#1a4480" },
  { key: "Poetry",      pt: "Poesia",     prefix: "P", tile: "#2c5f9e" },
  { key: "History",     pt: "História",   prefix: "C", tile: "#1d3a6e" },
  { key: "Religion",    pt: "Religião",   prefix: "A", tile: "#3a5c8c" },
  { key: "Travel",      pt: "Viagens",    prefix: "D", tile: "#446aa3" },
  { key: "Drama",       pt: "Teatro",     prefix: "T", tile: "#234876" },
  { key: "Education",   pt: "Educação",   prefix: "J", tile: "#2a5187" },
  { key: "Philosophy",  pt: "Filosofia",  prefix: "B", tile: "#1e3565" },
];

// UI strings keyed by lang.
window.LIBRARY_I18N = {
  en: {
    site: "The J.A. Freitas Library",
    tagline: "Founded in 1964 — over 12,000 works documenting the Portuguese experience",
    nav_home: "Library", nav_authors: "Authors", nav_subjects: "Subjects", nav_search: "Search",
    new_arrivals: "Recent additions",
    new_arrivals_sub: "Catalogued this month",
    hero_kicker: "Featured this week",
    view_book: "View record",
    by: "by",
    on_shelves: "books on the shelves",
    browse_by: "Browse by subject",
    browse_by_sub: "Eight categories spanning the collection",
    authors_h: "Authors",
    authors_sub: "Catalogued writers in the collection",
    books_count: "books",
    book_count_one: "book",
    show_all: "Show full catalogue →",
    detail_record: "Catalogue record",
    detail_published: "Published",
    detail_publisher: "Publisher",
    detail_subject: "Subject",
    detail_call: "Call number",
    detail_notes: "Notes",
    detail_digital: "Digital copy available",
    detail_no_digital: "No digital copy located",
    detail_other: "Other titles by this author",
    detail_view: "Open in catalogue",
    cover_unavailable: "Cover unavailable",
    search_placeholder: "Search titles, authors, call numbers…",
    search_results: "results",
    search_no_results: "Nothing matches that query.",
    lang_label: "EN",
    lang_other: "PT",
    placeholder_cover_top: "BIBLIOTECA",
    placeholder_cover_mid: "no cover yet",
    footer: "Catalogued by hand. Cross-referenced with BNP, LoC, Google Books, and Internet Archive.",
    sect_authors: "By author",
    sect_subjects: "By subject",
    new_label: "NEW",
  },
  pt: {
    site: "Biblioteca J.A. Freitas",
    tagline: "Fundada em 1964 — mais de 12.000 obras a documentar a experiência portuguesa",
    nav_home: "Acervo", nav_authors: "Autores", nav_subjects: "Assuntos", nav_search: "Pesquisar",
    new_arrivals: "Aquisições recentes",
    new_arrivals_sub: "Catalogados este mês",
    hero_kicker: "Em destaque",
    view_book: "Ver registo",
    by: "por",
    on_shelves: "livros nas estantes",
    browse_by: "Navegar por assunto",
    browse_by_sub: "Oito categorias que abrangem o acervo",
    authors_h: "Autores",
    authors_sub: "Escritores catalogados",
    books_count: "livros",
    book_count_one: "livro",
    show_all: "Ver catálogo completo →",
    detail_record: "Registo bibliográfico",
    detail_published: "Publicado",
    detail_publisher: "Editora",
    detail_subject: "Assunto",
    detail_call: "Cota",
    detail_notes: "Notas",
    detail_digital: "Cópia digital disponível",
    detail_no_digital: "Sem cópia digital localizada",
    detail_other: "Outras obras deste autor",
    detail_view: "Abrir no catálogo",
    cover_unavailable: "Sem capa",
    search_placeholder: "Procurar títulos, autores, cotas…",
    search_results: "resultados",
    search_no_results: "Nenhum resultado.",
    lang_label: "PT",
    lang_other: "EN",
    placeholder_cover_top: "BIBLIOTECA",
    placeholder_cover_mid: "sem capa",
    footer: "Catalogado à mão. Referenciado com BNP, LoC, Google Books e Internet Archive.",
    sect_authors: "Por autor",
    sect_subjects: "Por assunto",
    new_label: "NOVO",
  }
};
